routes/web.php
<?php

use App\Http\Controllers\CatalogController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('catalogs',CatalogController::class);

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Self_;

class Catalog extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'url_path',
    ];

    protected $casts = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function imageable()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    use HasFactory;

    protected $table = 'images';

    protected $fillable = [
      'name',
      'imageable_id',
      'imageable_type',
    ];

    protected $casts = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function image()
    {
        return $this->morphTo();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ApiCatalogController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\CatalogResource;
use App\Models\Catalog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ApiCatalogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $catalogs = Catalog::query()->with('imageable')->get()->toArray();

        return CatalogResource::collection($catalogs)->response();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function show(int $id): \Symfony\Component\HttpFoundation\BinaryFileResponse
    {
        $res = Catalog::findOrFail($id);
        $catalog = public_path('storage/files/') . $res->url_path;

        return Response::download($catalog,'PDF',[
            "Content-Type: application/json;charset=utf-8"
        ]);

//        $html = mb_convert_encoding($catalog, 'HTML-ENTITIES', 'UTF-8');
//        $html_decode = html_entity_decode($html);
//
//        return response()->file($html_decode, [
//            'Content-Type' => 'application/pdf;'
//        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Catalog;
use App\Models\Image;
use App\Services\ImagesService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CatalogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $catalogs = Catalog::query()->with('imageable')->get();
        return view('catalogs.index', compact('catalogs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $forms = $request->only('title','image','file');
        $rules = [
            'title' => 'required|string',
            'image' => 'required|image|mimes:jpeg,png|max:2048',
            'file' => 'required',
        ];

        $error = Validator::make($forms,$rules);

        $res = new Catalog;
        $res->name = $request->title;

        if($request->hasFile('file')){
            $file     = $request->file('file');
            $filename = time() . '_' . $file->getClientOriginalName();
            $file->move(public_path('storage/files/'), $filename);
            $res->url_path = $filename;
        }

        $res->save();

        if($request->hasFile('image')){

            $files= $request->file('image');
            ImagesService::save($res, $files, $res->id);
        }


        return redirect()->route('catalogs.index')->with(['success' => 'Каталог успешно создан']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id)
    {
        if (!$id) {
            return back()->withErrors(['msg' => 'Ошибка удаления!'])->withInput();
        }

        $res = Catalog::query()->findOrFail($id);
        $res->imageable()->where('imageable_id',$id)->delete();
        $res->delete();

        return redirect()->back()->with(['success' => 'Каталог успешно удален']);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/catalogs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container ">
        <div class="row">
            <div class="col-sm-8 tags">
                <div class="header">
                    <h1>Создайте новый каталог</h1>
                </div>

                <form id="formAdd" action="{{ route('catalogs.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="nameCatalog">Название каталога</label>
                        <input type="text" name="title" class="form-control" id="nameCatalog">
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="fileCatalog">Файл каталога</label>
                                <input type="file" name="file" multiple class="form-control-file" id="fileCatalog">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="imageCatalog">Картинка каталога</label>
                                <input type="file" name="image" multiple class="form-control-file" id="imageCatalog">
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Создать</button>
                </form>
            </div>
        </div>


        <hr>
        &nbsp;
        @include('errors')

        <div class="container">
            <table class="table">

                <thead class="thead-dark">

                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название каталога</th>
                    <th scope="col">Картинка каталога</th>
                    <th scope="col">Действия</th>
                </tr>

                </thead>
                <tbody>
                <?php $num = 1; ?>
                @foreach($catalogs as $catalog)
                <tr>
                    <th scope="row">{{$num++}}</th>
                    <td>{{$catalog->name}}</td>
                    @if($catalog->imageable['name'] == null)
                        <td>
                            <span>Not found</span>
                        </td>
                    @else
                        <td>
                            <img src="{{ asset('storage/catalogs/' . $catalog->imageable['name']) }}"
                                 alt="image"
                                 style="width: 100px;height: 100px">
                        </td>
                    @endif
                    <td>
                        <form action="{{ route('catalogs.destroy' , $catalog->id ) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button><i class="far fa-trash delete" aria-hidden="true"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach

                </tbody>

            </table>
        </div>
    </div>
@endsection

resources/views/errors.blade.php
@if ( $errors->any())
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{--{{ $errors->first() }}--}}
                <ul>
                    @foreach( $errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif
@if ( session('success'))
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ session()->get('success') }}
            </div>
        </div>
    </div>
@endif

resources/views/layouts/_includes/css_new_files.blade.php
<link rel="stylesheet" type="text/css" href="{{ url('bower-components/bootstrap/dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('bower-components/font-awesome/css/fontawesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/app.css') }}" />

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

resources/views/layouts/_includes/footer.blade.php
<div class="container-fluid footer">
    <div id="copyright" class="copyright col-sm-12 col-xs-12 text-center">
        <span>Copyright © Mavinx - PDF 2020-<?php echo date('Y');?> . All right reserved.</span>
    </div>
</div>

@section('scripts')

    <!-- Scripts -->
    <script type="text/javascript" src="{{ url('js/app.js') }}"></script>

    {{-- Bower components js --}}
    <script type="text/javascript" src="{{ url('bower-components/jquery/dist/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('bower-components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
@endsection

resources/views/layouts/_includes/head.blade.php
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta name="theme-color" content="#ffffff">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }} @yield('title')</title>

<!-- Favicon section -->
<link rel="icon" type="image/png" href="{{ url('/main_layout/images/favicons/lara.png') }}" sizes="32x32">
<link rel="icon" type="image/png" href="{{ url('/main_layout/images/favicons/lara.png') }}" sizes="16x16">
<link rel="manifest" href="{{ url('/main_layout/images/favicons/lara.json') }}">
<link rel="mask-icon" href="{{ url('/main_layout/images/favicons/lara.svg') }}" color="#073a85">

<!-- Styles -->
@include('layouts._includes.css_new_files')

@stack('styles')

<script>

</script>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Styles css and head pge -->
    @include('layouts._includes.head')
</head>
<body>
    <section>
        <div id="app">
            <div class="container">

                @yield('content')

                @include('layouts._includes.footer')
            </div>
        </div>
    </section>

    @yield('scripts')

    @stack('scripts')

</body>
</html>